import os
import sys
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

class GeminiClient:
    """
    Lightweight, high-performance client for Google Gemini REST API.
    Operates via direct HTTPS requests to bypass gRPC platform restrictions
    and provide reliable, deterministic latency.
    """
    BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

    def __init__(self, api_key: str = None):
        self.api_key = api_key or API_KEY
        if not self.api_key or self.api_key == "YOUR_GEMINI_API_KEY_HERE":
            raise ValueError(
                "GEMINI_API_KEY is not set. Please set it in your .env file or pass it to GeminiClient."
            )

    def embed_text(
        self,
        text: str,
        task_type: str = "RETRIEVAL_DOCUMENT",
        model: str = "models/gemini-embedding-001",
        output_dim: int = 768,
    ) -> list[float]:
        """
        Generate a single embedding vector for the provided text.
        Task types: RETRIEVAL_DOCUMENT, RETRIEVAL_QUERY, SEMANTIC_SIMILARITY, etc.
        """
        url = f"{self.BASE_URL}/{model}:embedContent?key={self.api_key}"
        payload = {
            "content": {"parts": [{"text": text}]},
            "taskType": task_type,
            "outputDimensionality": output_dim,
        }
        
        response = requests.post(url, json=payload, timeout=30)
        if response.status_code != 200:
            raise RuntimeError(f"Embedding API error [{response.status_code}]: {response.text}")
            
        data = response.json()
        return data.get("embedding", {}).get("values", [])

    def batch_embed_texts(
        self,
        texts: list[str],
        task_type: str = "RETRIEVAL_DOCUMENT",
        model: str = "models/gemini-embedding-001",
        output_dim: int = 768,
        batch_size: int = 50,
    ) -> list[list[float]]:
        """
        Generate embeddings in batches using the batchEmbedContents API endpoint.
        """
        url = f"{self.BASE_URL}/{model}:batchEmbedContents?key={self.api_key}"
        all_embeddings = []

        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            requests_payload = [
                {
                    "model": model,
                    "content": {"parts": [{"text": text}]},
                    "taskType": task_type,
                    "outputDimensionality": output_dim,
                }
                for text in batch
            ]

            response = requests.post(url, json={"requests": requests_payload}, timeout=60)
            if response.status_code != 200:
                raise RuntimeError(
                    f"Batch embedding error [{response.status_code}]: {response.text}"
                )

            data = response.json()
            embeddings = [item.get("values", []) for item in data.get("embeddings", [])]
            all_embeddings.extend(embeddings)

        return all_embeddings

    def generate_answer(
        self,
        prompt: str,
        model: str = "gemini-2.5-flash",
        temperature: float = 0.2,
    ) -> str:
        """
        Generates text using Google Gemini LLM.
        """
        url = f"{self.BASE_URL}/models/{model}:generateContent?key={self.api_key}"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature,
            },
        }

        response = requests.post(url, json=payload, timeout=60)
        if response.status_code != 200:
            raise RuntimeError(f"Generation API error [{response.status_code}]: {response.text}")

        data = response.json()
        try:
            candidates = data.get("candidates", [])
            if not candidates:
                return "No response generated by the model."
            return candidates[0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError) as e:
            raise RuntimeError(f"Unexpected response format: {data}") from e

    def generate_answer_stream(
        self,
        prompt: str,
        model: str = "gemini-2.5-flash",
        temperature: float = 0.2,
    ):
        """
        Streams generated text from Google Gemini LLM using Server-Sent Events (SSE).
        Yields text chunks as strings.
        """
        import json
        url = f"{self.BASE_URL}/models/{model}:streamGenerateContent?key={self.api_key}&alt=sse"
        payload = {
            "contents": [{"parts": [{"text": prompt}]}],
            "generationConfig": {
                "temperature": temperature,
            },
        }

        response = requests.post(url, json=payload, stream=True, timeout=60)
        if response.status_code != 200:
            raise RuntimeError(f"Streaming API error [{response.status_code}]: {response.text}")

        for line in response.iter_lines():
            if not line:
                continue
            line_str = line.decode("utf-8")
            if line_str.startswith("data: "):
                data_json = line_str[6:].strip()
                try:
                    data = json.loads(data_json)
                    candidates = data.get("candidates", [])
                    if candidates:
                        parts = candidates[0].get("content", {}).get("parts", [])
                        for part in parts:
                            text_piece = part.get("text", "")
                            if text_piece:
                                yield text_piece
                except json.JSONDecodeError:
                    continue

    def extract_pdf_multimodal(self, pdf_bytes: bytes, instruction: str = None) -> str:
        """
        Uses Gemini 2.5 Flash's native multimodal capabilities to transcribe
        scanned, image-only, or handwritten PDF slices.
        """
        import base64

        prompt = instruction or (
            "You are an expert document transcriber. Transcribe all text, code snippets, "
            "bullet points, diagrams, and explanations from these pages accurately and completely. "
            "Organize your transcription with clear markdown headers indicating page numbers like '## Page X'."
        )
        b64_data = base64.b64encode(pdf_bytes).decode("utf-8")

        url = f"{self.BASE_URL}/models/gemini-2.5-flash:generateContent?key={self.api_key}"
        payload = {
            "contents": [
                {
                    "parts": [
                        {"text": prompt},
                        {"inline_data": {"mime_type": "application/pdf", "data": b64_data}},
                    ]
                }
            ],
            "generationConfig": {
                "temperature": 0.1,
            },
        }

        response = requests.post(url, json=payload, timeout=90)
        if response.status_code != 200:
            raise RuntimeError(f"Multimodal PDF extraction error [{response.status_code}]: {response.text}")

        data = response.json()
        try:
            return data["candidates"][0]["content"]["parts"][0]["text"]
        except (KeyError, IndexError) as e:
            raise RuntimeError(f"Unexpected response structure: {data}") from e
