import os
import sys
import requests
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

API_KEY = os.getenv("GEMINI_API_KEY")

class GeminiClient:
    """
    Lightweight, high-performance client for Google Gemini REST API.
    Operates via direct HTTPS requests to bypass gRPC platform restrictions
    and provide reliable, deterministic latency.
    """
    BASE_URL = "https://generativelanguage.googleapis.com/v1beta"

    def __init__(self, api_key: str = None):
        self.api_key = api_key or API_KEY
        if not self.api_key or self.api_key == "YOUR_GEMINI_API_KEY_HERE":
            raise ValueError(
                "GEMINI_API_KEY is not set. Please set it in your .env file or pass it to GeminiClient."
            )

    def embed_text(
        self,
        text: str,
        task_type: str = "RETRIEVAL_DOCUMENT",
        model: str = "models/gemini-embedding-001",
        output_dim: int = 768,
    ) -> list[float]:
        """
        Generate a single embedding vector for the provided text.
        Task types: RETRIEVAL_DOCUMENT, RETRIEVAL_QUERY, SEMANTIC_SIMILARITY, etc.
        """
        url = f"{self.BASE_URL}/{model}:embedContent?key={self.api_key}"
        payload = {
            "content": {"parts": [{"text": text}]},
            "taskType": task_type,
            "outputDimensionality": output_dim,
        }
        
        response = requests.post(url, json=payload, timeout=30)
        if response.status_code != 200:
            raise RuntimeError(f"Embedding API error [{response.status_code}]: {response.text}")
            
        data = response.json()
        return data.get("embedding", {}).get("values", [])

    def batch_embed_texts(
        self,
        texts: list[str],
        task_type: str = "RETRIEVAL_DOCUMENT",
        model: str = "models/gemini-embedding-001",
        output_dim: int = 768,
        batch_size: int = 50,
    ) -> list[list[float]]:
        """
        Generate embeddings in batches using the batchEmbedContents API endpoint.
        """
        url = f"{self.BASE_URL}/{model}:batchEmbedContents?key={self.api_key}"
        all_embeddings = []

        for i in range(0, len(texts), batch_size):
            batch = texts[i : i + batch_size]
            requests_payload = [
                {
                    "model": model,
                    "content": {"parts": [{"text": text}]},
                    "taskType": task_type,
                    "outputDimensionality": output_dim,
                }
                for text in batch
            ]

            response = requests.post(url, json={"requests": requests_payload}, timeout=60)
            if response.status_code != 200:
                raise RuntimeError(
                    f"Batch embedding error [{response.status_code}]: {response.text}"
                )

            data = response.json()
            embeddings = [item.get("values", []) for item in data.get("embeddings", [])]
            all_embeddings.extend(embeddings)

        return all_embeddings

    def generate_answer(
        self,
        prompt: str,
        model: str = "gemini-3.5-flash",
        temperature: float = 0.2,
    ) -> str:
        """
        Generates text using Google Gemini LLM with automatic model fallback on quota limits.
        """
        candidate_models = [model] + [
            m for m in ["gemini-3.5-flash", "gemini-3-flash-preview", "gemini-flash-latest", "gemini-2.5-flash"]
            if m != model
        ]

        last_error = None
        for current_model in candidate_models:
            url = f"{self.BASE_URL}/models/{current_model}:generateContent?key={self.api_key}"
            payload = {
                "contents": [{"parts": [{"text": prompt}]}],
                "generationConfig": {
                    "temperature": temperature,
                },
            }

            try:
                response = requests.post(url, json=payload, timeout=60)
                if response.status_code == 200:
                    data = response.json()
                    candidates = data.get("candidates", [])
                    if not candidates:
                        return "No response generated by the model."
                    return candidates[0]["content"]["parts"][0]["text"]
                elif response.status_code in [429, 503, 404]:
                    last_error = f"{current_model} returned {response.status_code}"
                    continue
                else:
                    last_error = f"{current_model} error [{response.status_code}]: {response.text}"
            except Exception as e:
                last_error = str(e)
                continue

        raise RuntimeError(f"All Gemini generation models failed. Last error: {last_error}")

    def generate_answer_stream(
        self,
        prompt: str,
        model: str = "gemini-3.5-flash",
        temperature: float = 0.2,
    ):
        """
        Streams generated text from Google Gemini LLM using Server-Sent Events (SSE).
        Includes automatic model fallback on 429 quota exhaustion.
        Yields text chunks as strings.
        """
        import json

        candidate_models = [model] + [
            m for m in ["gemini-3.5-flash", "gemini-3-flash-preview", "gemini-flash-latest"]
            if m != model
        ]

        for current_model in candidate_models:
            url = f"{self.BASE_URL}/models/{current_model}:streamGenerateContent?key={self.api_key}&alt=sse"
            payload = {
                "contents": [{"parts": [{"text": prompt}]}],
                "generationConfig": {
                    "temperature": temperature,
                },
            }

            try:
                response = requests.post(url, json=payload, stream=True, timeout=(10, 30))
                if response.status_code == 200:
                    yielded_any = False
                    for line in response.iter_lines():
                        if not line:
                            continue
                        line_str = line.decode("utf-8")
                        if line_str.startswith("data: "):
                            data_json = line_str[6:].strip()
                            try:
                                data = json.loads(data_json)
                                candidates = data.get("candidates", [])
                                if candidates:
                                    parts = candidates[0].get("content", {}).get("parts", [])
                                    for part in parts:
                                        text_piece = part.get("text", "")
                                        if text_piece:
                                            yielded_any = True
                                            yield text_piece
                            except json.JSONDecodeError:
                                continue
                    if yielded_any:
                        return
                elif response.status_code in [429, 503, 404]:
                    continue
            except Exception:
                continue

        # Fallback to non-streaming if all stream endpoints fail
        fallback_text = self.generate_answer(prompt, model="gemini-3.5-flash", temperature=temperature)
        yield fallback_text

    def extract_pdf_multimodal(
        self,
        pdf_bytes: bytes,
        instruction: str = None,
        preferred_model: str = "gemini-3.5-flash",
    ) -> str:
        """
        Uses Gemini's native multimodal capabilities to transcribe
        scanned, image-only, or handwritten PDF slices.
        Includes automatic model fallback and retry backoff on 429 quota exhaustion.
        """
        import base64
        import time

        prompt = instruction or (
            "You are an expert document transcriber. Transcribe all text, code snippets, "
            "bullet points, diagrams, and explanations from these pages accurately and completely. "
            "Organize your transcription with clear markdown headers indicating page numbers like '## Page X'."
        )
        b64_data = base64.b64encode(pdf_bytes).decode("utf-8")

        candidate_models = [preferred_model] + [
            m for m in ["gemini-3.5-flash", "gemini-3-flash-preview", "gemini-flash-latest", "gemini-2.5-flash"]
            if m != preferred_model
        ]

        last_error = None
        for model in candidate_models:
            url = f"{self.BASE_URL}/models/{model}:generateContent?key={self.api_key}"
            payload = {
                "contents": [
                    {
                        "parts": [
                            {"text": prompt},
                            {"inline_data": {"mime_type": "application/pdf", "data": b64_data}},
                        ]
                    }
                ],
                "generationConfig": {
                    "temperature": 0.1,
                },
            }

            # Retry up to 3 times for temporary rate limits
            for attempt in range(3):
                try:
                    response = requests.post(url, json=payload, timeout=90)
                    if response.status_code == 200:
                        data = response.json()
                        candidates = data.get("candidates", [])
                        if candidates:
                            return candidates[0]["content"]["parts"][0]["text"]
                        return ""

                    if response.status_code in [429, 503]:
                        # Temporary rate limit or service spike: wait and retry
                        time.sleep(5 * (attempt + 1))
                        continue

                    # If model not found or permanent error, break to next model
                    last_error = f"{model} returned [{response.status_code}]: {response.text[:200]}"
                    break
                except Exception as e:
                    last_error = str(e)
                    time.sleep(3)

        raise RuntimeError(f"Multimodal PDF extraction failed across all models. Last error: {last_error}")

